using Microsoft.EntityFrameworkCore.Migrations;
using Npgsql.EntityFrameworkCore.PostgreSQL.Metadata;

#nullable disable

namespace Persistance.Migrations
{
    /// <inheritdoc />
    public partial class id_added_to_branch : Migration
    {
        /// <inheritdoc />
        protected override void Up(MigrationBuilder migrationBuilder)
        {
            // 1. Safe Drop: Find whatever the PK is called and drop it
            migrationBuilder.Sql(@"
        DO $$ 
        DECLARE 
            pk_name text;
        BEGIN 
            SELECT constraint_name INTO pk_name 
            FROM information_schema.table_constraints 
            WHERE table_name = 'branches' AND table_schema = 'kwarehouse' AND constraint_type = 'PRIMARY KEY';
            
            IF pk_name IS NOT NULL THEN
                EXECUTE 'ALTER TABLE kwarehouse.branches DROP CONSTRAINT ' || pk_name;
            END IF;
        END $$;");

            // 2. Add 'id' column as nullable first
            migrationBuilder.AddColumn<int>(
                name: "id",
                schema: "kwarehouse",
                table: "branches",
                type: "integer",
                nullable: true);

            // 3. Fill existing rows with numbers
            migrationBuilder.Sql(@"
        DO $$ 
        DECLARE 
            temp_seq_val int := 1;
            r RECORD;
        BEGIN
            FOR r IN SELECT * FROM kwarehouse.branches LOOP
                UPDATE kwarehouse.branches SET id = temp_seq_val WHERE branch_code = r.branch_code;
                temp_seq_val := temp_seq_val + 1;
            END LOOP;
        END $$;");

            // 4. Force NOT NULL and Identity using Raw SQL
            // This bypasses EF Core's attempt to combine the commands incorrectly
            migrationBuilder.Sql(@"
        ALTER TABLE kwarehouse.branches ALTER COLUMN id SET NOT NULL;
        ALTER TABLE kwarehouse.branches ALTER COLUMN id ADD GENERATED BY DEFAULT AS IDENTITY;
    ");

            // 5. Set new PK
            migrationBuilder.AddPrimaryKey(
                name: "PK_branches",
                schema: "kwarehouse",
                table: "branches",
                column: "id");

            // 6. Create Unique Index for BranchCode
            migrationBuilder.CreateIndex(
                name: "IX_branches_branch_code",
                schema: "kwarehouse",
                table: "branches",
                column: "branch_code",
                unique: true);
        }

        /// <inheritdoc />
        protected override void Down(MigrationBuilder migrationBuilder)
        {
            // 1. Drop the new PK we created (which we named PK_branches in the Up method)
            migrationBuilder.DropPrimaryKey(
                name: "PK_branches",
                schema: "kwarehouse",
                table: "branches");

            migrationBuilder.DropIndex(
                name: "IX_branches_branch_code",
                schema: "kwarehouse",
                table: "branches");

            // 2. Remove the id column
            migrationBuilder.DropColumn(
                name: "id",
                schema: "kwarehouse",
                table: "branches");

            // 3. Put back the old column (if you actually want to revert)
            migrationBuilder.AddColumn<string>(
                name: "branchdescarabic",
                schema: "kwarehouse",
                table: "branches",
                type: "text",
                nullable: true);

            // 4. Re-establish the original Primary Key on branch_code
            // Note: Re-creating it as 'branches_pkey' to match how it was before
            migrationBuilder.AddPrimaryKey(
                name: "branches_pkey",
                schema: "kwarehouse",
                table: "branches",
                column: "branch_code");
        }
    }
}
