// <auto-generated />
using System;
using Microsoft.EntityFrameworkCore;
using Microsoft.EntityFrameworkCore.Infrastructure;
using Microsoft.EntityFrameworkCore.Migrations;
using Microsoft.EntityFrameworkCore.Storage.ValueConversion;
using Npgsql.EntityFrameworkCore.PostgreSQL.Metadata;
using Persistance;

#nullable disable

namespace Persistance.Migrations
{
    [DbContext(typeof(InventoryManagementDbContext))]
    [Migration("20260219092029_init")]
    partial class init
    {
        /// <inheritdoc />
        protected override void BuildTargetModel(ModelBuilder modelBuilder)
        {
#pragma warning disable 612, 618
            modelBuilder
                .HasDefaultSchema("KWAREHOUSE")
                .HasAnnotation("ProductVersion", "7.0.20")
                .HasAnnotation("Relational:MaxIdentifierLength", 63);

            NpgsqlModelBuilderExtensions.UseIdentityByDefaultColumns(modelBuilder);

            modelBuilder.HasSequence<int>("seq_item_category_code");

            modelBuilder.Entity("Domain.Entities.Branch", b =>
                {
                    b.Property<string>("BranchCode")
                        .HasColumnType("character")
                        .HasColumnName("branch_code");

                    b.Property<string>("BranchDesc")
                        .HasColumnType("text")
                        .HasColumnName("branch_desc");

                    b.HasKey("BranchCode");

                    b.ToTable("branches", "kwarehouse");
                });

            modelBuilder.Entity("Domain.Entities.Department", b =>
                {
                    b.Property<int>("DepCode")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("integer")
                        .HasColumnName("dep_code");

                    NpgsqlPropertyBuilderExtensions.UseIdentityByDefaultColumn(b.Property<int>("DepCode"));

                    b.Property<string>("DepDesc")
                        .HasColumnType("text")
                        .HasColumnName("dep_desc");

                    b.Property<string>("GeneralManeg")
                        .HasColumnType("text")
                        .HasColumnName("general_maneg");

                    b.Property<string>("ManegSupCode")
                        .HasColumnType("text")
                        .HasColumnName("maneg_supcode");

                    b.Property<string>("SectorCode")
                        .HasColumnType("text")
                        .HasColumnName("sector_code");

                    b.HasKey("DepCode");

                    b.ToTable("departments", "kwarehouse");
                });

            modelBuilder.Entity("Domain.Entities.EmpEgx", b =>
                {
                    b.Property<int>("DepCode")
                        .HasColumnType("integer")
                        .HasColumnName("dep_code");

                    b.Property<int>("EmpCode")
                        .HasColumnType("integer")
                        .HasColumnName("emp_code");

                    b.Property<string>("BranchCode")
                        .HasColumnType("text")
                        .HasColumnName("branch_code");

                    b.Property<string>("EmpName")
                        .HasColumnType("text")
                        .HasColumnName("emp_name");

                    b.HasKey("DepCode", "EmpCode");

                    b.ToTable("emp_egx", "kwarehouse");
                });

            modelBuilder.Entity("Domain.Entities.HInvTrans", b =>
                {
                    b.Property<int>("StoreCode")
                        .HasColumnType("integer")
                        .HasColumnName("store_code");

                    b.Property<int>("TrType")
                        .HasColumnType("integer")
                        .HasColumnName("tr_type");

                    b.Property<DateTime>("TrDate")
                        .HasColumnType("timestamp with time zone")
                        .HasColumnName("tr_date");

                    b.Property<int>("TrNum")
                        .HasColumnType("integer")
                        .HasColumnName("tr_num");

                    b.Property<int>("TrSerial")
                        .HasColumnType("integer")
                        .HasColumnName("tr_serial");

                    b.Property<string>("ItemCode")
                        .HasColumnType("character varying(5)")
                        .HasColumnName("item_code");

                    b.Property<int?>("BillNum")
                        .HasColumnType("integer")
                        .HasColumnName("bill_num");

                    b.Property<DateTime?>("DeliverDate")
                        .HasColumnType("timestamp with time zone")
                        .HasColumnName("deliver_date");

                    b.Property<int?>("DeliverNo")
                        .HasColumnType("integer")
                        .HasColumnName("deliver_no");

                    b.Property<int?>("DepCode")
                        .HasColumnType("integer")
                        .HasColumnName("dep_code");

                    b.Property<int?>("EmpCode")
                        .HasColumnType("integer")
                        .HasColumnName("emp_code");

                    b.Property<int?>("FromToStore")
                        .HasColumnType("integer")
                        .HasColumnName("from_to_store");

                    b.Property<decimal?>("ItemPrice")
                        .HasColumnType("numeric")
                        .HasColumnName("item_price");

                    b.Property<decimal>("ItemQnt")
                        .HasColumnType("numeric")
                        .HasColumnName("item_qnt");

                    b.Property<DateTime?>("OrderDate")
                        .HasColumnType("timestamp with time zone")
                        .HasColumnName("order_date");

                    b.Property<int?>("SuplierCode")
                        .HasColumnType("integer")
                        .HasColumnName("suplier_code");

                    b.Property<DateTime?>("TrDate2")
                        .HasColumnType("timestamp with time zone")
                        .HasColumnName("tr_date2");

                    b.Property<int?>("TrNum2")
                        .HasColumnType("integer")
                        .HasColumnName("tr_num2");

                    b.HasKey("StoreCode", "TrType", "TrDate", "TrNum", "TrSerial", "ItemCode");

                    b.HasIndex("ItemCode");

                    b.HasIndex("SuplierCode");

                    b.ToTable("h_inv_trans", "kwarehouse");
                });

            modelBuilder.Entity("Domain.Entities.InvTrans", b =>
                {
                    b.Property<int>("StoreCode")
                        .HasColumnType("integer")
                        .HasColumnName("store_code");

                    b.Property<int>("TrType")
                        .HasColumnType("integer")
                        .HasColumnName("tr_type");

                    b.Property<DateTime>("TrDate")
                        .HasColumnType("timestamp with time zone")
                        .HasColumnName("tr_date");

                    b.Property<int>("TrNum")
                        .HasColumnType("integer")
                        .HasColumnName("tr_num");

                    b.Property<int>("TrSerial")
                        .HasColumnType("integer")
                        .HasColumnName("tr_serial");

                    b.Property<string>("ItemCode")
                        .HasColumnType("character varying(5)")
                        .HasColumnName("item_code");

                    b.Property<int?>("BillNum")
                        .HasColumnType("integer")
                        .HasColumnName("bill_num");

                    b.Property<DateTime?>("DeliverDate")
                        .HasColumnType("timestamp with time zone")
                        .HasColumnName("deliver_date");

                    b.Property<int?>("DeliverNo")
                        .HasColumnType("integer")
                        .HasColumnName("deliver_no");

                    b.Property<int?>("DepCode")
                        .HasColumnType("integer")
                        .HasColumnName("dep_code");

                    b.Property<int?>("EmpCode")
                        .HasColumnType("integer")
                        .HasColumnName("emp_code");

                    b.Property<int?>("FromToStore")
                        .HasColumnType("integer")
                        .HasColumnName("from_to_store");

                    b.Property<decimal?>("ItemPrice")
                        .HasColumnType("numeric")
                        .HasColumnName("item_price");

                    b.Property<decimal>("ItemQnt")
                        .HasColumnType("numeric")
                        .HasColumnName("item_qnt");

                    b.Property<DateTime?>("OrderDate")
                        .HasColumnType("timestamp with time zone")
                        .HasColumnName("order_date");

                    b.Property<int?>("SuplierCode")
                        .HasColumnType("integer")
                        .HasColumnName("suplier_code");

                    b.Property<DateTime?>("TrDate2")
                        .HasColumnType("timestamp with time zone")
                        .HasColumnName("tr_date2");

                    b.Property<int?>("TrNum2")
                        .HasColumnType("integer")
                        .HasColumnName("tr_num2");

                    b.HasKey("StoreCode", "TrType", "TrDate", "TrNum", "TrSerial", "ItemCode");

                    b.HasIndex("ItemCode");

                    b.HasIndex("SuplierCode");

                    b.HasIndex("DepCode", "EmpCode");

                    b.ToTable("inv_trans", "kwarehouse");
                });

            modelBuilder.Entity("Domain.Entities.InvUser", b =>
                {
                    b.Property<int>("UserCode")
                        .HasColumnType("integer")
                        .HasColumnName("user_code");

                    b.Property<string>("Prog01")
                        .HasColumnType("text")
                        .HasColumnName("prog01");

                    b.Property<string>("Prog02")
                        .HasColumnType("text")
                        .HasColumnName("prog02");

                    b.Property<string>("Prog03")
                        .HasColumnType("text")
                        .HasColumnName("prog03");

                    b.Property<string>("Prog11")
                        .HasColumnType("text")
                        .HasColumnName("prog11");

                    b.Property<string>("Prog12")
                        .HasColumnType("text")
                        .HasColumnName("prog12");

                    b.Property<string>("Prog13")
                        .HasColumnType("text")
                        .HasColumnName("prog13");

                    b.Property<string>("Prog14")
                        .HasColumnType("text")
                        .HasColumnName("prog14");

                    b.Property<string>("Prog21")
                        .HasColumnType("text")
                        .HasColumnName("prog21");

                    b.Property<string>("Prog22")
                        .HasColumnType("text")
                        .HasColumnName("prog22");

                    b.Property<string>("Prog23")
                        .HasColumnType("text")
                        .HasColumnName("prog23");

                    b.Property<string>("Prog24")
                        .HasColumnType("text")
                        .HasColumnName("prog24");

                    b.Property<string>("Prog25")
                        .HasColumnType("text")
                        .HasColumnName("prog25");

                    b.Property<string>("Prog29")
                        .HasColumnType("text")
                        .HasColumnName("prog29");

                    b.Property<string>("Prog31")
                        .HasColumnType("text")
                        .HasColumnName("prog31");

                    b.Property<string>("Prog32")
                        .HasColumnType("text")
                        .HasColumnName("prog32");

                    b.Property<string>("Prog33")
                        .HasColumnType("text")
                        .HasColumnName("prog33");

                    b.Property<string>("Prog34")
                        .HasColumnType("text")
                        .HasColumnName("prog34");

                    b.Property<string>("Prog35")
                        .HasColumnType("text")
                        .HasColumnName("prog35");

                    b.Property<string>("UserName")
                        .HasColumnType("text")
                        .HasColumnName("user_name");

                    b.Property<string>("UserPasswd")
                        .HasColumnType("text")
                        .HasColumnName("user_passwd");

                    b.HasKey("UserCode");

                    b.ToTable("inv_users", "kwarehouse");
                });

            modelBuilder.Entity("Domain.Entities.Item", b =>
                {
                    b.Property<string>("CatgryCode")
                        .HasMaxLength(2)
                        .HasColumnType("character varying(2)")
                        .HasColumnName("catgry_code");

                    b.Property<string>("ItemCode")
                        .ValueGeneratedOnAdd()
                        .HasMaxLength(5)
                        .HasColumnType("character varying(5)")
                        .HasColumnName("item_code")
                        .HasDefaultValueSql("NULL");

                    b.Property<string>("Barecode")
                        .HasColumnType("text")
                        .HasColumnName("barecode");

                    b.Property<string>("ItemDesc")
                        .HasColumnType("text")
                        .HasColumnName("item_desc");

                    b.Property<decimal?>("RecallPrc")
                        .HasColumnType("numeric")
                        .HasColumnName("recall_prc");

                    b.Property<decimal?>("RecallQnt")
                        .HasColumnType("numeric")
                        .HasColumnName("recall_qnt");

                    b.HasKey("CatgryCode", "ItemCode");

                    b.ToTable("items", "kwarehouse");
                });

            modelBuilder.Entity("Domain.Entities.ItemBalance", b =>
                {
                    b.Property<int>("StoreCode")
                        .HasColumnType("integer")
                        .HasColumnName("store_code");

                    b.Property<DateTime>("BalDate")
                        .HasColumnType("timestamp with time zone")
                        .HasColumnName("bal_date");

                    b.Property<string>("ItemCode")
                        .HasColumnType("text")
                        .HasColumnName("item_code");

                    b.Property<decimal>("CurrentBal")
                        .HasColumnType("numeric")
                        .HasColumnName("current_bal");

                    b.Property<decimal>("ItemBack")
                        .HasColumnType("numeric")
                        .HasColumnName("item_back");

                    b.Property<decimal>("ItemBack2")
                        .HasColumnType("numeric")
                        .HasColumnName("item_back2");

                    b.Property<decimal>("ItemFrom")
                        .HasColumnType("numeric")
                        .HasColumnName("item_from");

                    b.Property<decimal>("ItemIn")
                        .HasColumnType("numeric")
                        .HasColumnName("item_in");

                    b.Property<decimal>("ItemOut")
                        .HasColumnType("numeric")
                        .HasColumnName("item_out");

                    b.Property<decimal>("ItemScrap")
                        .HasColumnType("numeric")
                        .HasColumnName("item_scrap");

                    b.Property<decimal>("ItemTo")
                        .HasColumnType("numeric")
                        .HasColumnName("item_to");

                    b.Property<decimal>("OpenBal")
                        .HasColumnType("numeric")
                        .HasColumnName("open_bal");

                    b.HasKey("StoreCode", "BalDate", "ItemCode");

                    b.ToTable("item_balance", "kwarehouse");
                });

            modelBuilder.Entity("Domain.Entities.ItemCard", b =>
                {
                    b.Property<int?>("StoreCode")
                        .HasColumnType("integer")
                        .HasColumnName("store_code");

                    b.Property<string>("ItemCode")
                        .HasColumnType("text")
                        .HasColumnName("item_code");

                    b.Property<int?>("CardSerial")
                        .HasColumnType("integer")
                        .HasColumnName("card_serial");

                    b.Property<decimal?>("CardBalance")
                        .HasColumnType("numeric")
                        .HasColumnName("card_balance");

                    b.Property<DateTime?>("CardDate")
                        .HasColumnType("timestamp with time zone")
                        .HasColumnName("card_date");

                    b.Property<string>("CardMemo")
                        .HasColumnType("text")
                        .HasColumnName("card_memo");

                    b.Property<int?>("InNum")
                        .HasColumnType("integer")
                        .HasColumnName("in_num");

                    b.Property<decimal?>("InPrice")
                        .HasColumnType("numeric")
                        .HasColumnName("in_price");

                    b.Property<decimal?>("InQnt")
                        .HasColumnType("numeric")
                        .HasColumnName("in_qnt");

                    b.Property<string>("ItemDesc")
                        .HasColumnType("text")
                        .HasColumnName("item_desc");

                    b.Property<int?>("OutNum")
                        .HasColumnType("integer")
                        .HasColumnName("out_num");

                    b.Property<decimal?>("OutQnt")
                        .HasColumnType("numeric")
                        .HasColumnName("out_qnt");

                    b.HasKey("StoreCode", "ItemCode", "CardSerial");

                    b.ToTable("item_card", "kwarehouse");
                });

            modelBuilder.Entity("Domain.Entities.ItemCategory", b =>
                {
                    b.Property<string>("CatgryCode")
                        .HasColumnType("text")
                        .HasColumnName("catgry_code");

                    b.Property<string>("CatgryDesc")
                        .HasColumnType("text")
                        .HasColumnName("catgry_desc");

                    b.HasKey("CatgryCode");

                    b.ToTable("item_category", "kwarehouse");
                });

            modelBuilder.Entity("Domain.Entities.MonthlyBalance", b =>
                {
                    b.Property<int>("StoreCode")
                        .HasColumnType("integer")
                        .HasColumnName("store_code");

                    b.Property<int>("BalYear")
                        .HasColumnType("integer")
                        .HasColumnName("bal_year");

                    b.Property<int>("BalMonth")
                        .HasColumnType("integer")
                        .HasColumnName("bal_month");

                    b.Property<string>("ItemCode")
                        .HasColumnType("text")
                        .HasColumnName("item_code");

                    b.Property<decimal>("CurrentBal")
                        .HasColumnType("numeric")
                        .HasColumnName("current_bal");

                    b.Property<decimal>("ItemBack")
                        .HasColumnType("numeric")
                        .HasColumnName("item_back");

                    b.Property<decimal>("ItemBack2")
                        .HasColumnType("numeric")
                        .HasColumnName("item_back2");

                    b.Property<decimal>("ItemFrom")
                        .HasColumnType("numeric")
                        .HasColumnName("item_from");

                    b.Property<decimal>("ItemIn")
                        .HasColumnType("numeric")
                        .HasColumnName("item_in");

                    b.Property<decimal>("ItemOut")
                        .HasColumnType("numeric")
                        .HasColumnName("item_out");

                    b.Property<decimal>("ItemScrap")
                        .HasColumnType("numeric")
                        .HasColumnName("item_scrap");

                    b.Property<decimal>("ItemTo")
                        .HasColumnType("numeric")
                        .HasColumnName("item_to");

                    b.Property<decimal>("OpenBal")
                        .HasColumnType("numeric")
                        .HasColumnName("open_bal");

                    b.HasKey("StoreCode", "BalYear", "BalMonth", "ItemCode");

                    b.ToTable("monthly_balance", "kwarehouse");
                });

            modelBuilder.Entity("Domain.Entities.MonthlyConsum", b =>
                {
                    b.Property<int>("StoreCode")
                        .HasColumnType("integer")
                        .HasColumnName("store_code");

                    b.Property<int>("ConsumYear")
                        .HasColumnType("integer")
                        .HasColumnName("consum_year");

                    b.Property<int>("ConsumMonth")
                        .HasColumnType("integer")
                        .HasColumnName("consum_month");

                    b.Property<int>("DepCode")
                        .HasColumnType("integer")
                        .HasColumnName("dep_code");

                    b.Property<string>("ItemCode")
                        .HasColumnType("text")
                        .HasColumnName("item_code");

                    b.Property<decimal>("ConsumAvg")
                        .HasColumnType("numeric")
                        .HasColumnName("consum_avg");

                    b.Property<decimal>("ConsumQnt")
                        .HasColumnType("numeric")
                        .HasColumnName("consum_qnt");

                    b.HasKey("StoreCode", "ConsumYear", "ConsumMonth", "DepCode", "ItemCode");

                    b.ToTable("monthly_consum", "kwarehouse");
                });

            modelBuilder.Entity("Domain.Entities.OpenBalance", b =>
                {
                    b.Property<int>("StoreCode")
                        .HasColumnType("integer")
                        .HasColumnName("store_code");

                    b.Property<DateTime>("OpenDate")
                        .HasColumnType("timestamp with time zone")
                        .HasColumnName("open_date");

                    b.Property<string>("ItemCode")
                        .HasColumnType("text")
                        .HasColumnName("item_code");

                    b.Property<decimal>("OpenBal")
                        .HasColumnType("numeric")
                        .HasColumnName("open_bal");

                    b.Property<string>("RelayFlag")
                        .HasColumnType("text")
                        .HasColumnName("relay_flag");

                    b.HasKey("StoreCode", "OpenDate", "ItemCode");

                    b.ToTable("open_balance", "kwarehouse");
                });

            modelBuilder.Entity("Domain.Entities.Store", b =>
                {
                    b.Property<int>("StoreCode")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("integer")
                        .HasColumnName("store_code");

                    NpgsqlPropertyBuilderExtensions.UseIdentityByDefaultColumn(b.Property<int>("StoreCode"));

                    b.Property<int>("BackNum")
                        .HasColumnType("integer")
                        .HasColumnName("back_num");

                    b.Property<int>("BackNum2")
                        .HasColumnType("integer")
                        .HasColumnName("back_num2");

                    b.Property<int>("InNum")
                        .HasColumnType("integer")
                        .HasColumnName("in_num");

                    b.Property<int>("OutNum")
                        .HasColumnType("integer")
                        .HasColumnName("out_num");

                    b.Property<int>("ScrapNum")
                        .HasColumnType("integer")
                        .HasColumnName("scrap_num");

                    b.Property<string>("StoreDesc")
                        .HasColumnType("text")
                        .HasColumnName("store_desc");

                    b.Property<DateTime?>("SysDate")
                        .HasColumnType("timestamp with time zone")
                        .HasColumnName("sys_date");

                    b.Property<string>("SysLock")
                        .HasColumnType("text")
                        .HasColumnName("sys_lock");

                    b.Property<int>("ToNum")
                        .HasColumnType("integer")
                        .HasColumnName("to_num");

                    b.HasKey("StoreCode");

                    b.ToTable("stores", "kwarehouse");
                });

            modelBuilder.Entity("Domain.Entities.Supplier", b =>
                {
                    b.Property<int>("SuplierCode")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("integer")
                        .HasColumnName("suplier_code");

                    NpgsqlPropertyBuilderExtensions.UseIdentityByDefaultColumn(b.Property<int>("SuplierCode"));

                    b.Property<string>("SuplierActivity")
                        .HasColumnType("text")
                        .HasColumnName("suplier_activity");

                    b.Property<string>("SuplierAddress")
                        .HasColumnType("text")
                        .HasColumnName("suplier_address");

                    b.Property<string>("SuplierDesc")
                        .HasColumnType("text")
                        .HasColumnName("suplier_desc");

                    b.Property<string>("SuplierEmail")
                        .HasColumnType("text")
                        .HasColumnName("suplier_email");

                    b.Property<string>("SuplierFax")
                        .HasColumnType("text")
                        .HasColumnName("suplier_fax");

                    b.Property<string>("SuplierTel")
                        .HasColumnType("text")
                        .HasColumnName("suplier_tel");

                    b.HasKey("SuplierCode");

                    b.ToTable("supplier", "kwarehouse");
                });

            modelBuilder.Entity("Domain.Entities.SysMessg", b =>
                {
                    b.Property<int>("MsgCode")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("integer")
                        .HasColumnName("msg_code");

                    NpgsqlPropertyBuilderExtensions.UseIdentityByDefaultColumn(b.Property<int>("MsgCode"));

                    b.Property<string>("MsgDesc")
                        .HasColumnType("text")
                        .HasColumnName("msg_desc");

                    b.HasKey("MsgCode");

                    b.ToTable("sys_messg", "kwarehouse");
                });

            modelBuilder.Entity("Domain.Entities.HInvTrans", b =>
                {
                    b.HasOne("Domain.Entities.Item", "Item")
                        .WithMany()
                        .HasForeignKey("ItemCode")
                        .HasPrincipalKey("ItemCode")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.HasOne("Domain.Entities.Supplier", "Supplier")
                        .WithMany()
                        .HasForeignKey("SuplierCode");

                    b.Navigation("Item");

                    b.Navigation("Supplier");
                });

            modelBuilder.Entity("Domain.Entities.InvTrans", b =>
                {
                    b.HasOne("Domain.Entities.Department", "Department")
                        .WithMany()
                        .HasForeignKey("DepCode");

                    b.HasOne("Domain.Entities.Item", "Item")
                        .WithMany()
                        .HasForeignKey("ItemCode")
                        .HasPrincipalKey("ItemCode")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.HasOne("Domain.Entities.Supplier", "Supplier")
                        .WithMany()
                        .HasForeignKey("SuplierCode");

                    b.HasOne("Domain.Entities.EmpEgx", "Employee")
                        .WithMany()
                        .HasForeignKey("DepCode", "EmpCode");

                    b.Navigation("Department");

                    b.Navigation("Employee");

                    b.Navigation("Item");

                    b.Navigation("Supplier");
                });

            modelBuilder.Entity("Domain.Entities.InvUser", b =>
                {
                    b.HasOne("Domain.Entities.EmpEgx", "Employee")
                        .WithMany()
                        .HasForeignKey("UserCode")
                        .HasPrincipalKey("EmpCode")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.Navigation("Employee");
                });

            modelBuilder.Entity("Domain.Entities.Item", b =>
                {
                    b.HasOne("Domain.Entities.ItemCategory", "ItemCategory")
                        .WithMany("Items")
                        .HasForeignKey("CatgryCode")
                        .OnDelete(DeleteBehavior.Restrict)
                        .IsRequired();

                    b.Navigation("ItemCategory");
                });

            modelBuilder.Entity("Domain.Entities.ItemCategory", b =>
                {
                    b.Navigation("Items");
                });
#pragma warning restore 612, 618
        }
    }
}
