using Microsoft.EntityFrameworkCore.Migrations;
using Npgsql.EntityFrameworkCore.PostgreSQL.Metadata;

#nullable disable

namespace Persistance.Migrations
{
    /// <inheritdoc />
    public partial class addedIdToDepartment : Migration
    {
        /// <inheritdoc />
        protected override void Up(MigrationBuilder migrationBuilder)
        {
            // 1. Drop existing FK and PK
            // 1. Safe Drop: Find and drop the FK and then the PK
            migrationBuilder.Sql(@"
    DO $$ 
    DECLARE 
        fk_name text;
    BEGIN 
        SELECT constraint_name INTO fk_name 
        FROM information_schema.key_column_usage 
        WHERE table_name = 'inv_trans' 
          AND table_schema = 'kwarehouse' 
          AND column_name = 'dep_code';

        IF fk_name IS NOT NULL THEN
            EXECUTE 'ALTER TABLE kwarehouse.inv_trans DROP CONSTRAINT ' || fk_name;
        END IF;
    END $$;");

            // Now drop the Primary Key (using the same logic to be safe)
            migrationBuilder.Sql(@"
    DO $$ 
    DECLARE pk_name text;
    BEGIN 
        SELECT constraint_name INTO pk_name 
        FROM information_schema.table_constraints 
        WHERE table_name = 'departments' AND table_schema = 'kwarehouse' AND constraint_type = 'PRIMARY KEY';
        
        IF pk_name IS NOT NULL THEN
            EXECUTE 'ALTER TABLE kwarehouse.departments DROP CONSTRAINT ' || pk_name;
        END IF;
    END $$;");

          

            // 2. Add 'id' as nullable first so we can fill it
            migrationBuilder.AddColumn<int>(
                name: "id",
                schema: "kwarehouse",
                table: "departments",
                type: "integer",
                nullable: true);

            // 3. Fill 'id' with numbers based on dep_code
            migrationBuilder.Sql(@"
        UPDATE kwarehouse.departments SET id = sub.row_num
        FROM (SELECT dep_code, row_number() OVER (ORDER BY dep_code) as row_num FROM kwarehouse.departments) sub
        WHERE kwarehouse.departments.dep_code = sub.dep_code;");

            // 4. Force NOT NULL and Identity using Raw SQL (Avoids the 55000 error)
            migrationBuilder.Sql(@"
        ALTER TABLE kwarehouse.departments ALTER COLUMN id SET NOT NULL;
        ALTER TABLE kwarehouse.departments ALTER COLUMN id ADD GENERATED BY DEFAULT AS IDENTITY;
    ");

            // 5. Apply new Primary Key to 'id'
            migrationBuilder.AddPrimaryKey(
                name: "PK_departments",
                schema: "kwarehouse",
                table: "departments",
                column: "id");

            // 6. Fix branch_code column type as requested by your original migration
            migrationBuilder.AlterColumn<string>(
                name: "branch_code",
                schema: "kwarehouse",
                table: "branches",
                type: "text",
                nullable: false);

            // 7. Keep dep_code unique
            migrationBuilder.CreateIndex(
                name: "IX_departments_dep_code",
                schema: "kwarehouse",
                table: "departments",
                column: "dep_code",
                unique: true);

            //// 8. Re-add Foreign Key
            migrationBuilder.AddForeignKey(
                  name: "FK_inv_trans_departments_dep_code",
                  schema: "kwarehouse",
                  table: "inv_trans",
                  column: "dep_code",
                  principalSchema: "kwarehouse",
                  principalTable: "departments", // Fixed parameter name
                  principalColumn: "dep_code");
        }

        /// <inheritdoc />
        protected override void Down(MigrationBuilder migrationBuilder)
        {
            migrationBuilder.DropForeignKey(
                name: "FK_inv_trans_departments_dep_code",
                schema: "kwarehouse",
                table: "inv_trans");

            migrationBuilder.DropPrimaryKey(
                name: "PK_departments",
                schema: "kwarehouse",
                table: "departments");

            migrationBuilder.DropIndex(
                name: "IX_departments_dep_code",
                schema: "kwarehouse",
                table: "departments");

            migrationBuilder.DropColumn(
                name: "id",
                schema: "kwarehouse",
                table: "departments");

            migrationBuilder.AlterColumn<int>(
                name: "dep_code",
                schema: "kwarehouse",
                table: "departments",
                type: "integer",
                nullable: false,
                oldClrType: typeof(int),
                oldType: "integer")
                .Annotation("Npgsql:ValueGenerationStrategy", NpgsqlValueGenerationStrategy.IdentityByDefaultColumn);

            migrationBuilder.AlterColumn<string>(
                name: "branch_code",
                schema: "kwarehouse",
                table: "branches",
                type: "character(1)",
                nullable: false,
                oldClrType: typeof(string),
                oldType: "text");

            migrationBuilder.AddPrimaryKey(
                name: "PK_departments",
                schema: "kwarehouse",
                table: "departments",
                column: "dep_code");

            migrationBuilder.AddForeignKey(
                name: "FK_inv_trans_departments_dep_code",
                schema: "kwarehouse",
                table: "inv_trans",
                column: "dep_code",
                principalSchema: "kwarehouse",
                principalTable: "departments",
                principalColumn: "dep_code");
        }
    }
}
