// <auto-generated />
using System;
using Microsoft.EntityFrameworkCore;
using Microsoft.EntityFrameworkCore.Infrastructure;
using Microsoft.EntityFrameworkCore.Migrations;
using Microsoft.EntityFrameworkCore.Storage.ValueConversion;
using Npgsql.EntityFrameworkCore.PostgreSQL.Metadata;
using Persistance;

#nullable disable

namespace Persistance.Migrations
{
    [DbContext(typeof(InventoryManagementDbContext))]
    [Migration("20260330082829_permissionaction")]
    partial class permissionaction
    {
        /// <inheritdoc />
        protected override void BuildTargetModel(ModelBuilder modelBuilder)
        {
#pragma warning disable 612, 618
            modelBuilder
                .HasDefaultSchema("KWAREHOUSE")
                .HasAnnotation("ProductVersion", "8.0.1")
                .HasAnnotation("Relational:MaxIdentifierLength", 63);

            NpgsqlModelBuilderExtensions.UseIdentityByDefaultColumns(modelBuilder);

            modelBuilder.HasSequence<int>("seq_item_category_code");

            modelBuilder.Entity("Domain.Entities.ApplicationRole", b =>
                {
                    b.Property<string>("Id")
                        .HasColumnType("text")
                        .HasColumnName("id");

                    b.Property<string>("ConcurrencyStamp")
                        .IsConcurrencyToken()
                        .HasColumnType("text")
                        .HasColumnName("concurrencystamp");

                    b.Property<DateTime>("CreatedAt")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("timestamp with time zone")
                        .HasColumnName("createdat")
                        .HasDefaultValueSql("CURRENT_TIMESTAMP");

                    b.Property<string>("Description")
                        .HasMaxLength(500)
                        .HasColumnType("character varying(500)")
                        .HasColumnName("description");

                    b.Property<bool>("IsActive")
                        .HasColumnType("boolean")
                        .HasColumnName("isactive");

                    b.Property<bool>("IsSystemRole")
                        .HasColumnType("boolean")
                        .HasColumnName("issystemrole");

                    b.Property<int>("Level")
                        .HasColumnType("integer")
                        .HasColumnName("level");

                    b.Property<string>("Name")
                        .HasMaxLength(256)
                        .HasColumnType("character varying(256)")
                        .HasColumnName("name");

                    b.Property<string>("NormalizedName")
                        .HasMaxLength(256)
                        .HasColumnType("character varying(256)")
                        .HasColumnName("normalizedname");

                    b.Property<DateTime?>("UpdatedAt")
                        .HasColumnType("timestamp with time zone")
                        .HasColumnName("updatedat");

                    b.HasKey("Id");

                    b.HasIndex("NormalizedName")
                        .IsUnique()
                        .HasDatabaseName("RoleNameIndex");

                    b.ToTable("aspnetroles", "kwarehouse");
                });

            modelBuilder.Entity("Domain.Entities.ApplicationUser", b =>
                {
                    b.Property<string>("Id")
                        .HasColumnType("text")
                        .HasColumnName("id");

                    b.Property<int>("AccessFailedCount")
                        .HasColumnType("integer")
                        .HasColumnName("accessfailedcount");

                    b.Property<string>("ConcurrencyStamp")
                        .IsConcurrencyToken()
                        .HasColumnType("text")
                        .HasColumnName("concurrencystamp");

                    b.Property<DateTime>("CreatedAt")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("timestamp with time zone")
                        .HasColumnName("createdat")
                        .HasDefaultValueSql("CURRENT_TIMESTAMP");

                    b.Property<string>("Department")
                        .HasMaxLength(100)
                        .HasColumnType("character varying(100)")
                        .HasColumnName("department");

                    b.Property<string>("Email")
                        .HasMaxLength(256)
                        .HasColumnType("character varying(256)")
                        .HasColumnName("email");

                    b.Property<bool>("EmailConfirmed")
                        .HasColumnType("boolean")
                        .HasColumnName("emailconfirmed");

                    b.Property<int?>("EmployeeCode")
                        .HasColumnType("integer")
                        .HasColumnName("employeecode");

                    b.Property<string>("FirstName")
                        .HasMaxLength(100)
                        .HasColumnType("character varying(100)")
                        .HasColumnName("firstname");

                    b.Property<string>("FullName")
                        .HasMaxLength(200)
                        .HasColumnType("character varying(200)")
                        .HasColumnName("fullname");

                    b.Property<bool>("IsActive")
                        .HasColumnType("boolean")
                        .HasColumnName("isactive");

                    b.Property<DateTime?>("LastLoginAt")
                        .HasColumnType("timestamp with time zone")
                        .HasColumnName("lastloginat");

                    b.Property<string>("LastName")
                        .HasMaxLength(100)
                        .HasColumnType("character varying(100)")
                        .HasColumnName("lastname");

                    b.Property<bool>("LockoutEnabled")
                        .HasColumnType("boolean")
                        .HasColumnName("lockoutenabled");

                    b.Property<DateTimeOffset?>("LockoutEnd")
                        .HasColumnType("timestamp with time zone")
                        .HasColumnName("lockoutend");

                    b.Property<string>("NormalizedEmail")
                        .HasMaxLength(256)
                        .HasColumnType("character varying(256)")
                        .HasColumnName("normalizedemail");

                    b.Property<string>("NormalizedUserName")
                        .HasMaxLength(256)
                        .HasColumnType("character varying(256)")
                        .HasColumnName("normalizedusername");

                    b.Property<string>("PasswordHash")
                        .HasColumnType("text")
                        .HasColumnName("passwordhash");

                    b.Property<string>("PhoneNumber")
                        .HasColumnType("text")
                        .HasColumnName("phonenumber");

                    b.Property<bool>("PhoneNumberConfirmed")
                        .HasColumnType("boolean")
                        .HasColumnName("phonenumberconfirmed");

                    b.Property<string>("SecurityStamp")
                        .HasColumnType("text")
                        .HasColumnName("securitystamp");

                    b.Property<bool>("TwoFactorEnabled")
                        .HasColumnType("boolean")
                        .HasColumnName("twofactorenabled");

                    b.Property<string>("UserName")
                        .HasMaxLength(256)
                        .HasColumnType("character varying(256)")
                        .HasColumnName("username");

                    b.HasKey("Id");

                    b.HasIndex("NormalizedEmail")
                        .HasDatabaseName("EmailIndex");

                    b.HasIndex("NormalizedUserName")
                        .IsUnique()
                        .HasDatabaseName("UserNameIndex");

                    b.ToTable("aspnetusers", "kwarehouse");
                });

            modelBuilder.Entity("Domain.Entities.Branch", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("integer")
                        .HasColumnName("id");

                    NpgsqlPropertyBuilderExtensions.UseIdentityByDefaultColumn(b.Property<int>("Id"));

                    b.Property<string>("BranchCode")
                        .IsRequired()
                        .HasColumnType("text")
                        .HasColumnName("branch_code");

                    b.Property<string>("BranchDesc")
                        .HasColumnType("text")
                        .HasColumnName("branch_desc");

                    b.HasKey("Id");

                    b.HasIndex("BranchCode")
                        .IsUnique();

                    b.ToTable("branches", "kwarehouse");
                });

            modelBuilder.Entity("Domain.Entities.Department", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("integer")
                        .HasColumnName("id");

                    NpgsqlPropertyBuilderExtensions.UseIdentityByDefaultColumn(b.Property<int>("Id"));

                    b.Property<int>("DepCode")
                        .HasColumnType("integer")
                        .HasColumnName("dep_code");

                    b.Property<string>("DepDesc")
                        .HasColumnType("text")
                        .HasColumnName("dep_desc");

                    b.Property<string>("GeneralManeg")
                        .HasColumnType("text")
                        .HasColumnName("general_maneg");

                    b.Property<string>("ManegSupCode")
                        .HasColumnType("text")
                        .HasColumnName("maneg_supcode");

                    b.Property<string>("SectorCode")
                        .HasColumnType("text")
                        .HasColumnName("sector_code");

                    b.HasKey("Id");

                    b.HasIndex("DepCode")
                        .IsUnique();

                    b.ToTable("departments", "kwarehouse");
                });

            modelBuilder.Entity("Domain.Entities.EmpEgx", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("integer")
                        .HasColumnName("id");

                    NpgsqlPropertyBuilderExtensions.UseIdentityByDefaultColumn(b.Property<int>("Id"));

                    b.Property<string>("BranchCode")
                        .HasColumnType("text")
                        .HasColumnName("branch_code");

                    b.Property<int>("DepCode")
                        .HasColumnType("integer")
                        .HasColumnName("dep_code");

                    b.Property<int>("EmpCode")
                        .HasColumnType("integer")
                        .HasColumnName("emp_code");

                    b.Property<string>("EmpName")
                        .HasColumnType("text")
                        .HasColumnName("emp_name");

                    b.HasKey("Id");

                    b.HasIndex("DepCode", "EmpCode")
                        .IsUnique();

                    b.ToTable("emp_egx", "kwarehouse");
                });

            modelBuilder.Entity("Domain.Entities.HInvTrans", b =>
                {
                    b.Property<int>("StoreCode")
                        .HasColumnType("integer")
                        .HasColumnName("store_code");

                    b.Property<int>("TrType")
                        .HasColumnType("integer")
                        .HasColumnName("tr_type");

                    b.Property<DateTime>("TrDate")
                        .HasColumnType("timestamp with time zone")
                        .HasColumnName("tr_date");

                    b.Property<int>("TrNum")
                        .HasColumnType("integer")
                        .HasColumnName("tr_num");

                    b.Property<int>("TrSerial")
                        .HasColumnType("integer")
                        .HasColumnName("tr_serial");

                    b.Property<string>("ItemCode")
                        .HasColumnType("character varying(5)")
                        .HasColumnName("item_code");

                    b.Property<int?>("BillNum")
                        .HasColumnType("integer")
                        .HasColumnName("bill_num");

                    b.Property<DateTime?>("DeliverDate")
                        .HasColumnType("timestamp with time zone")
                        .HasColumnName("deliver_date");

                    b.Property<int?>("DeliverNo")
                        .HasColumnType("integer")
                        .HasColumnName("deliver_no");

                    b.Property<int?>("DepCode")
                        .HasColumnType("integer")
                        .HasColumnName("dep_code");

                    b.Property<int?>("EmpCode")
                        .HasColumnType("integer")
                        .HasColumnName("emp_code");

                    b.Property<int?>("FromToStore")
                        .HasColumnType("integer")
                        .HasColumnName("from_to_store");

                    b.Property<decimal?>("ItemPrice")
                        .HasColumnType("numeric")
                        .HasColumnName("item_price");

                    b.Property<decimal>("ItemQnt")
                        .HasColumnType("numeric")
                        .HasColumnName("item_qnt");

                    b.Property<DateTime?>("OrderDate")
                        .HasColumnType("timestamp with time zone")
                        .HasColumnName("order_date");

                    b.Property<int?>("SuplierCode")
                        .HasColumnType("integer")
                        .HasColumnName("suplier_code");

                    b.Property<DateTime?>("TrDate2")
                        .HasColumnType("timestamp with time zone")
                        .HasColumnName("tr_date2");

                    b.Property<int?>("TrNum2")
                        .HasColumnType("integer")
                        .HasColumnName("tr_num2");

                    b.HasKey("StoreCode", "TrType", "TrDate", "TrNum", "TrSerial", "ItemCode");

                    b.HasIndex("ItemCode");

                    b.HasIndex("SuplierCode");

                    b.ToTable("h_inv_trans", "kwarehouse");
                });

            modelBuilder.Entity("Domain.Entities.InvTrans", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("integer")
                        .HasColumnName("id");

                    NpgsqlPropertyBuilderExtensions.UseIdentityByDefaultColumn(b.Property<int>("Id"));

                    b.Property<int?>("BillNum")
                        .HasColumnType("integer")
                        .HasColumnName("billnum");

                    b.Property<DateTime?>("DeliverDate")
                        .HasColumnType("timestamp with time zone")
                        .HasColumnName("deliverdate");

                    b.Property<int?>("DeliverNo")
                        .HasColumnType("integer")
                        .HasColumnName("deliverno");

                    b.Property<int?>("DepCode")
                        .HasColumnType("integer")
                        .HasColumnName("depcode");

                    b.Property<int?>("EmpCode")
                        .HasColumnType("integer")
                        .HasColumnName("empcode");

                    b.Property<int?>("EmployeeId")
                        .HasColumnType("integer")
                        .HasColumnName("employeeid");

                    b.Property<int?>("FromToStore")
                        .HasColumnType("integer")
                        .HasColumnName("fromtostore");

                    b.Property<string>("ItemCode")
                        .HasColumnType("character varying(5)")
                        .HasColumnName("itemcode");

                    b.Property<decimal?>("ItemPrice")
                        .HasColumnType("numeric")
                        .HasColumnName("itemprice");

                    b.Property<decimal>("ItemQnt")
                        .HasColumnType("numeric")
                        .HasColumnName("itemqnt");

                    b.Property<DateTime?>("OrderDate")
                        .HasColumnType("timestamp with time zone")
                        .HasColumnName("orderdate");

                    b.Property<int>("StoreCode")
                        .HasColumnType("integer")
                        .HasColumnName("storecode");

                    b.Property<int?>("SuplierCode")
                        .HasColumnType("integer")
                        .HasColumnName("supliercode");

                    b.Property<DateTime>("TrDate")
                        .HasColumnType("timestamp with time zone")
                        .HasColumnName("trdate");

                    b.Property<DateTime?>("TrDate2")
                        .HasColumnType("timestamp with time zone")
                        .HasColumnName("trdate2");

                    b.Property<int>("TrNum")
                        .HasColumnType("integer")
                        .HasColumnName("trnum");

                    b.Property<int?>("TrNum2")
                        .HasColumnType("integer")
                        .HasColumnName("trnum2");

                    b.Property<int>("TrSerial")
                        .HasColumnType("integer")
                        .HasColumnName("trserial");

                    b.Property<int>("TrType")
                        .HasColumnType("integer")
                        .HasColumnName("trtype");

                    b.HasKey("Id");

                    b.HasIndex("DepCode");

                    b.HasIndex("EmployeeId");

                    b.HasIndex("ItemCode");

                    b.HasIndex("SuplierCode");

                    b.HasIndex("StoreCode", "TrType", "TrDate", "TrNum", "TrSerial", "ItemCode")
                        .IsUnique();

                    b.ToTable("inv_trans", "kwarehouse");
                });

            modelBuilder.Entity("Domain.Entities.InvUser", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("integer")
                        .HasColumnName("id");

                    NpgsqlPropertyBuilderExtensions.UseIdentityByDefaultColumn(b.Property<int>("Id"));

                    b.Property<string>("Prog01")
                        .HasColumnType("text")
                        .HasColumnName("prog01");

                    b.Property<string>("Prog02")
                        .HasColumnType("text")
                        .HasColumnName("prog02");

                    b.Property<string>("Prog03")
                        .HasColumnType("text")
                        .HasColumnName("prog03");

                    b.Property<string>("Prog11")
                        .HasColumnType("text")
                        .HasColumnName("prog11");

                    b.Property<string>("Prog12")
                        .HasColumnType("text")
                        .HasColumnName("prog12");

                    b.Property<string>("Prog13")
                        .HasColumnType("text")
                        .HasColumnName("prog13");

                    b.Property<string>("Prog14")
                        .HasColumnType("text")
                        .HasColumnName("prog14");

                    b.Property<string>("Prog21")
                        .HasColumnType("text")
                        .HasColumnName("prog21");

                    b.Property<string>("Prog22")
                        .HasColumnType("text")
                        .HasColumnName("prog22");

                    b.Property<string>("Prog23")
                        .HasColumnType("text")
                        .HasColumnName("prog23");

                    b.Property<string>("Prog24")
                        .HasColumnType("text")
                        .HasColumnName("prog24");

                    b.Property<string>("Prog25")
                        .HasColumnType("text")
                        .HasColumnName("prog25");

                    b.Property<string>("Prog29")
                        .HasColumnType("text")
                        .HasColumnName("prog29");

                    b.Property<string>("Prog31")
                        .HasColumnType("text")
                        .HasColumnName("prog31");

                    b.Property<string>("Prog32")
                        .HasColumnType("text")
                        .HasColumnName("prog32");

                    b.Property<string>("Prog33")
                        .HasColumnType("text")
                        .HasColumnName("prog33");

                    b.Property<string>("Prog34")
                        .HasColumnType("text")
                        .HasColumnName("prog34");

                    b.Property<string>("Prog35")
                        .HasColumnType("text")
                        .HasColumnName("prog35");

                    b.Property<int>("UserCode")
                        .HasColumnType("integer")
                        .HasColumnName("user_code");

                    b.Property<string>("UserName")
                        .HasColumnType("text")
                        .HasColumnName("user_name");

                    b.Property<string>("UserPasswd")
                        .HasColumnType("text")
                        .HasColumnName("user_passwd");

                    b.HasKey("Id");

                    b.HasIndex("UserCode")
                        .IsUnique();

                    b.ToTable("inv_users", "kwarehouse");
                });

            modelBuilder.Entity("Domain.Entities.Item", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("integer")
                        .HasColumnName("id");

                    NpgsqlPropertyBuilderExtensions.UseIdentityByDefaultColumn(b.Property<int>("Id"));

                    b.Property<string>("Barecode")
                        .HasColumnType("text")
                        .HasColumnName("barecode");

                    b.Property<int>("CatgryCode")
                        .HasColumnType("integer")
                        .HasColumnName("catgry_code");

                    b.Property<string>("ItemCode")
                        .IsRequired()
                        .ValueGeneratedOnAdd()
                        .HasMaxLength(5)
                        .HasColumnType("character varying(5)")
                        .HasColumnName("item_code")
                        .HasDefaultValueSql("NULL");

                    b.Property<string>("ItemDesc")
                        .HasColumnType("text")
                        .HasColumnName("item_desc");

                    b.Property<decimal>("MinimumQuantity")
                        .HasColumnType("numeric")
                        .HasColumnName("minimumquantity");

                    b.Property<decimal>("NotificationPercentage")
                        .HasColumnType("numeric")
                        .HasColumnName("notificationpercentage");

                    b.Property<decimal?>("RecallPrc")
                        .HasColumnType("numeric")
                        .HasColumnName("recall_prc");

                    b.Property<decimal?>("RecallQnt")
                        .HasColumnType("numeric")
                        .HasColumnName("recall_qnt");

                    b.HasKey("Id");

                    b.HasIndex("CatgryCode", "ItemCode")
                        .IsUnique();

                    b.ToTable("items", "kwarehouse");
                });

            modelBuilder.Entity("Domain.Entities.ItemBalance", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("integer")
                        .HasColumnName("id");

                    NpgsqlPropertyBuilderExtensions.UseIdentityByDefaultColumn(b.Property<int>("Id"));

                    b.Property<DateTime>("BalDate")
                        .HasColumnType("timestamp with time zone")
                        .HasColumnName("bal_date");

                    b.Property<decimal>("CurrentBal")
                        .HasColumnType("numeric")
                        .HasColumnName("current_bal");

                    b.Property<decimal>("ItemBack")
                        .HasColumnType("numeric")
                        .HasColumnName("item_back");

                    b.Property<decimal>("ItemBack2")
                        .HasColumnType("numeric")
                        .HasColumnName("item_back2");

                    b.Property<string>("ItemCode")
                        .HasColumnType("text")
                        .HasColumnName("item_code");

                    b.Property<decimal>("ItemFrom")
                        .HasColumnType("numeric")
                        .HasColumnName("item_from");

                    b.Property<decimal>("ItemIn")
                        .HasColumnType("numeric")
                        .HasColumnName("item_in");

                    b.Property<decimal>("ItemOut")
                        .HasColumnType("numeric")
                        .HasColumnName("item_out");

                    b.Property<decimal>("ItemScrap")
                        .HasColumnType("numeric")
                        .HasColumnName("item_scrap");

                    b.Property<decimal>("ItemTo")
                        .HasColumnType("numeric")
                        .HasColumnName("item_to");

                    b.Property<decimal>("OpenBal")
                        .HasColumnType("numeric")
                        .HasColumnName("open_bal");

                    b.Property<int>("StoreCode")
                        .HasColumnType("integer")
                        .HasColumnName("store_code");

                    b.HasKey("Id");

                    b.HasIndex("StoreCode", "BalDate", "ItemCode")
                        .IsUnique();

                    b.ToTable("item_balance", "kwarehouse");
                });

            modelBuilder.Entity("Domain.Entities.ItemCard", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("integer")
                        .HasColumnName("id");

                    NpgsqlPropertyBuilderExtensions.UseIdentityByDefaultColumn(b.Property<int>("Id"));

                    b.Property<decimal?>("CardBalance")
                        .HasColumnType("numeric")
                        .HasColumnName("card_balance");

                    b.Property<DateTime?>("CardDate")
                        .HasColumnType("timestamp with time zone")
                        .HasColumnName("card_date");

                    b.Property<string>("CardMemo")
                        .HasColumnType("text")
                        .HasColumnName("card_memo");

                    b.Property<int?>("CardSerial")
                        .HasColumnType("integer")
                        .HasColumnName("card_serial");

                    b.Property<int?>("InNum")
                        .HasColumnType("integer")
                        .HasColumnName("in_num");

                    b.Property<decimal?>("InPrice")
                        .HasColumnType("numeric")
                        .HasColumnName("in_price");

                    b.Property<decimal?>("InQnt")
                        .HasColumnType("numeric")
                        .HasColumnName("in_qnt");

                    b.Property<string>("ItemCode")
                        .HasColumnType("text")
                        .HasColumnName("item_code");

                    b.Property<string>("ItemDesc")
                        .HasColumnType("text")
                        .HasColumnName("item_desc");

                    b.Property<int?>("OutNum")
                        .HasColumnType("integer")
                        .HasColumnName("out_num");

                    b.Property<decimal?>("OutQnt")
                        .HasColumnType("numeric")
                        .HasColumnName("out_qnt");

                    b.Property<int?>("StoreCode")
                        .HasColumnType("integer")
                        .HasColumnName("store_code");

                    b.HasKey("Id");

                    b.HasIndex("StoreCode", "ItemCode", "CardSerial")
                        .IsUnique();

                    b.ToTable("item_card", "kwarehouse");
                });

            modelBuilder.Entity("Domain.Entities.ItemCategory", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("integer")
                        .HasColumnName("id");

                    NpgsqlPropertyBuilderExtensions.UseIdentityByDefaultColumn(b.Property<int>("Id"));

                    b.Property<int>("CatgryCode")
                        .HasColumnType("integer")
                        .HasColumnName("catgry_code");

                    b.Property<string>("CatgryDesc")
                        .HasColumnType("text")
                        .HasColumnName("catgry_desc");

                    b.HasKey("Id");

                    b.ToTable("item_category", "kwarehouse");
                });

            modelBuilder.Entity("Domain.Entities.MonthlyBalance", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("integer")
                        .HasColumnName("id");

                    NpgsqlPropertyBuilderExtensions.UseIdentityByDefaultColumn(b.Property<int>("Id"));

                    b.Property<int>("BalMonth")
                        .HasColumnType("integer")
                        .HasColumnName("bal_month");

                    b.Property<int>("BalYear")
                        .HasColumnType("integer")
                        .HasColumnName("bal_year");

                    b.Property<decimal>("CurrentBal")
                        .HasColumnType("numeric")
                        .HasColumnName("current_bal");

                    b.Property<decimal>("ItemBack")
                        .HasColumnType("numeric")
                        .HasColumnName("item_back");

                    b.Property<decimal>("ItemBack2")
                        .HasColumnType("numeric")
                        .HasColumnName("item_back2");

                    b.Property<string>("ItemCode")
                        .HasColumnType("text")
                        .HasColumnName("item_code");

                    b.Property<decimal>("ItemFrom")
                        .HasColumnType("numeric")
                        .HasColumnName("item_from");

                    b.Property<decimal>("ItemIn")
                        .HasColumnType("numeric")
                        .HasColumnName("item_in");

                    b.Property<decimal>("ItemOut")
                        .HasColumnType("numeric")
                        .HasColumnName("item_out");

                    b.Property<decimal>("ItemScrap")
                        .HasColumnType("numeric")
                        .HasColumnName("item_scrap");

                    b.Property<decimal>("ItemTo")
                        .HasColumnType("numeric")
                        .HasColumnName("item_to");

                    b.Property<decimal>("OpenBal")
                        .HasColumnType("numeric")
                        .HasColumnName("open_bal");

                    b.Property<int>("StoreCode")
                        .HasColumnType("integer")
                        .HasColumnName("store_code");

                    b.HasKey("Id");

                    b.HasIndex("StoreCode", "BalYear", "BalMonth", "ItemCode")
                        .IsUnique();

                    b.ToTable("monthly_balance", "kwarehouse");
                });

            modelBuilder.Entity("Domain.Entities.MonthlyConsum", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("integer")
                        .HasColumnName("id");

                    NpgsqlPropertyBuilderExtensions.UseIdentityByDefaultColumn(b.Property<int>("Id"));

                    b.Property<decimal>("ConsumAvg")
                        .HasColumnType("numeric")
                        .HasColumnName("consum_avg");

                    b.Property<int>("ConsumMonth")
                        .HasColumnType("integer")
                        .HasColumnName("consum_month");

                    b.Property<decimal>("ConsumQnt")
                        .HasColumnType("numeric")
                        .HasColumnName("consum_qnt");

                    b.Property<int>("ConsumYear")
                        .HasColumnType("integer")
                        .HasColumnName("consum_year");

                    b.Property<int>("DepCode")
                        .HasColumnType("integer")
                        .HasColumnName("dep_code");

                    b.Property<string>("ItemCode")
                        .HasColumnType("text")
                        .HasColumnName("item_code");

                    b.Property<int>("StoreCode")
                        .HasColumnType("integer")
                        .HasColumnName("store_code");

                    b.HasKey("Id");

                    b.HasIndex("StoreCode", "ConsumYear", "ConsumMonth", "DepCode", "ItemCode")
                        .IsUnique();

                    b.ToTable("monthly_consum", "kwarehouse");
                });

            modelBuilder.Entity("Domain.Entities.OpenBalance", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("integer")
                        .HasColumnName("id");

                    NpgsqlPropertyBuilderExtensions.UseIdentityByDefaultColumn(b.Property<int>("Id"));

                    b.Property<string>("ItemCode")
                        .HasColumnType("text")
                        .HasColumnName("item_code");

                    b.Property<decimal>("OpenBal")
                        .HasColumnType("numeric")
                        .HasColumnName("open_bal");

                    b.Property<DateTime>("OpenDate")
                        .HasColumnType("timestamp with time zone")
                        .HasColumnName("open_date");

                    b.Property<string>("RelayFlag")
                        .HasColumnType("text")
                        .HasColumnName("relay_flag");

                    b.Property<int>("StoreCode")
                        .HasColumnType("integer")
                        .HasColumnName("store_code");

                    b.HasKey("Id");

                    b.HasIndex("StoreCode", "OpenDate", "ItemCode")
                        .IsUnique();

                    b.ToTable("open_balance", "kwarehouse");
                });

            modelBuilder.Entity("Domain.Entities.RolePermission", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("integer")
                        .HasColumnName("id");

                    NpgsqlPropertyBuilderExtensions.UseIdentityByDefaultColumn(b.Property<int>("Id"));

                    b.Property<DateTime>("CreatedAt")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("timestamp with time zone")
                        .HasColumnName("createdat")
                        .HasDefaultValueSql("CURRENT_TIMESTAMP");

                    b.Property<bool>("IsAllowed")
                        .HasColumnType("boolean")
                        .HasColumnName("isallowed");

                    b.Property<string>("Module")
                        .IsRequired()
                        .HasMaxLength(100)
                        .HasColumnType("character varying(100)")
                        .HasColumnName("module");

                    b.Property<string>("PermissionCode")
                        .IsRequired()
                        .HasMaxLength(50)
                        .HasColumnType("character varying(50)")
                        .HasColumnName("permissioncode");

                    b.Property<string>("PermissionName")
                        .IsRequired()
                        .HasMaxLength(200)
                        .HasColumnType("character varying(200)")
                        .HasColumnName("permissionname");

                    b.Property<string>("RoleId")
                        .HasColumnType("text")
                        .HasColumnName("roleid");

                    b.HasKey("Id");

                    b.HasIndex("RoleId");

                    b.ToTable("rolepermissions", "kwarehouse");
                });

            modelBuilder.Entity("Domain.Entities.Store", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("integer")
                        .HasColumnName("id");

                    NpgsqlPropertyBuilderExtensions.UseIdentityByDefaultColumn(b.Property<int>("Id"));

                    b.Property<int>("BackNum")
                        .HasColumnType("integer")
                        .HasColumnName("back_num");

                    b.Property<int>("BackNum2")
                        .HasColumnType("integer")
                        .HasColumnName("back_num2");

                    b.Property<int>("InNum")
                        .HasColumnType("integer")
                        .HasColumnName("in_num");

                    b.Property<int>("OutNum")
                        .HasColumnType("integer")
                        .HasColumnName("out_num");

                    b.Property<int>("ScrapNum")
                        .HasColumnType("integer")
                        .HasColumnName("scrap_num");

                    b.Property<int>("StoreCode")
                        .HasColumnType("integer")
                        .HasColumnName("store_code");

                    b.Property<string>("StoreDesc")
                        .HasColumnType("text")
                        .HasColumnName("store_desc");

                    b.Property<DateTime?>("SysDate")
                        .HasColumnType("timestamp with time zone")
                        .HasColumnName("sys_date");

                    b.Property<string>("SysLock")
                        .HasColumnType("text")
                        .HasColumnName("sys_lock");

                    b.Property<int>("ToNum")
                        .HasColumnType("integer")
                        .HasColumnName("to_num");

                    b.HasKey("Id");

                    b.HasIndex("StoreCode")
                        .IsUnique();

                    b.ToTable("stores", "kwarehouse");
                });

            modelBuilder.Entity("Domain.Entities.Supplier", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("integer")
                        .HasColumnName("id");

                    NpgsqlPropertyBuilderExtensions.UseIdentityByDefaultColumn(b.Property<int>("Id"));

                    b.Property<string>("SuplierActivity")
                        .HasColumnType("text")
                        .HasColumnName("suplier_activity");

                    b.Property<string>("SuplierAddress")
                        .HasColumnType("text")
                        .HasColumnName("suplier_address");

                    b.Property<int>("SuplierCode")
                        .HasColumnType("integer")
                        .HasColumnName("suplier_code");

                    b.Property<string>("SuplierDesc")
                        .HasColumnType("text")
                        .HasColumnName("suplier_desc");

                    b.Property<string>("SuplierEmail")
                        .HasColumnType("text")
                        .HasColumnName("suplier_email");

                    b.Property<string>("SuplierFax")
                        .HasColumnType("text")
                        .HasColumnName("suplier_fax");

                    b.Property<string>("SuplierTel")
                        .HasColumnType("text")
                        .HasColumnName("suplier_tel");

                    b.HasKey("Id");

                    b.HasIndex("SuplierCode")
                        .IsUnique();

                    b.ToTable("supplier", "kwarehouse");
                });

            modelBuilder.Entity("Domain.Entities.SysMessg", b =>
                {
                    b.Property<int>("MsgCode")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("integer")
                        .HasColumnName("msg_code");

                    NpgsqlPropertyBuilderExtensions.UseIdentityByDefaultColumn(b.Property<int>("MsgCode"));

                    b.Property<string>("MsgDesc")
                        .HasColumnType("text")
                        .HasColumnName("msg_desc");

                    b.HasKey("MsgCode");

                    b.ToTable("sys_messg", "kwarehouse");
                });

            modelBuilder.Entity("Domain.Entities.UserRole", b =>
                {
                    b.Property<string>("UserId")
                        .HasColumnType("text")
                        .HasColumnName("user_id");

                    b.Property<string>("RoleId")
                        .HasColumnType("text")
                        .HasColumnName("role_id");

                    b.HasKey("UserId", "RoleId");

                    b.HasIndex("RoleId");

                    b.ToTable("user_roles", "kwarehouse");
                });

            modelBuilder.Entity("Microsoft.AspNetCore.Identity.IdentityRoleClaim<string>", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("integer")
                        .HasColumnName("id");

                    NpgsqlPropertyBuilderExtensions.UseIdentityByDefaultColumn(b.Property<int>("Id"));

                    b.Property<string>("ClaimType")
                        .HasColumnType("text")
                        .HasColumnName("claimtype");

                    b.Property<string>("ClaimValue")
                        .HasColumnType("text")
                        .HasColumnName("claimvalue");

                    b.Property<string>("RoleId")
                        .IsRequired()
                        .HasColumnType("text")
                        .HasColumnName("roleid");

                    b.HasKey("Id");

                    b.HasIndex("RoleId");

                    b.ToTable("aspnetroleclaims", "kwarehouse");
                });

            modelBuilder.Entity("Microsoft.AspNetCore.Identity.IdentityUserClaim<string>", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("integer")
                        .HasColumnName("id");

                    NpgsqlPropertyBuilderExtensions.UseIdentityByDefaultColumn(b.Property<int>("Id"));

                    b.Property<string>("ClaimType")
                        .HasColumnType("text")
                        .HasColumnName("claimtype");

                    b.Property<string>("ClaimValue")
                        .HasColumnType("text")
                        .HasColumnName("claimvalue");

                    b.Property<string>("UserId")
                        .IsRequired()
                        .HasColumnType("text")
                        .HasColumnName("userid");

                    b.HasKey("Id");

                    b.HasIndex("UserId");

                    b.ToTable("aspnetuserclaims", "kwarehouse");
                });

            modelBuilder.Entity("Microsoft.AspNetCore.Identity.IdentityUserLogin<string>", b =>
                {
                    b.Property<string>("LoginProvider")
                        .HasColumnType("text")
                        .HasColumnName("loginprovider");

                    b.Property<string>("ProviderKey")
                        .HasColumnType("text")
                        .HasColumnName("providerkey");

                    b.Property<string>("ProviderDisplayName")
                        .HasColumnType("text")
                        .HasColumnName("providerdisplayname");

                    b.Property<string>("UserId")
                        .IsRequired()
                        .HasColumnType("text")
                        .HasColumnName("userid");

                    b.HasKey("LoginProvider", "ProviderKey");

                    b.HasIndex("UserId");

                    b.ToTable("aspnetuserlogins", "kwarehouse");
                });

            modelBuilder.Entity("Microsoft.AspNetCore.Identity.IdentityUserRole<string>", b =>
                {
                    b.Property<string>("UserId")
                        .HasColumnType("text")
                        .HasColumnName("userid");

                    b.Property<string>("RoleId")
                        .HasColumnType("text")
                        .HasColumnName("roleid");

                    b.HasKey("UserId", "RoleId");

                    b.HasIndex("RoleId");

                    b.ToTable("aspnetuserroles", "kwarehouse");
                });

            modelBuilder.Entity("Microsoft.AspNetCore.Identity.IdentityUserToken<string>", b =>
                {
                    b.Property<string>("UserId")
                        .HasColumnType("text")
                        .HasColumnName("userid");

                    b.Property<string>("LoginProvider")
                        .HasColumnType("text")
                        .HasColumnName("loginprovider");

                    b.Property<string>("Name")
                        .HasColumnType("text")
                        .HasColumnName("name");

                    b.Property<string>("Value")
                        .HasColumnType("text")
                        .HasColumnName("value");

                    b.HasKey("UserId", "LoginProvider", "Name");

                    b.ToTable("aspnetusertokens", "kwarehouse");
                });

            modelBuilder.Entity("Domain.Entities.HInvTrans", b =>
                {
                    b.HasOne("Domain.Entities.Item", "Item")
                        .WithMany()
                        .HasForeignKey("ItemCode")
                        .HasPrincipalKey("ItemCode")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.HasOne("Domain.Entities.Supplier", "Supplier")
                        .WithMany()
                        .HasForeignKey("SuplierCode");

                    b.Navigation("Item");

                    b.Navigation("Supplier");
                });

            modelBuilder.Entity("Domain.Entities.InvTrans", b =>
                {
                    b.HasOne("Domain.Entities.Department", "Department")
                        .WithMany()
                        .HasForeignKey("DepCode")
                        .HasPrincipalKey("DepCode");

                    b.HasOne("Domain.Entities.EmpEgx", "Employee")
                        .WithMany()
                        .HasForeignKey("EmployeeId")
                        .OnDelete(DeleteBehavior.Restrict);

                    b.HasOne("Domain.Entities.Item", "Item")
                        .WithMany()
                        .HasForeignKey("ItemCode")
                        .HasPrincipalKey("ItemCode");

                    b.HasOne("Domain.Entities.Supplier", "Supplier")
                        .WithMany()
                        .HasForeignKey("SuplierCode")
                        .HasPrincipalKey("SuplierCode");

                    b.Navigation("Department");

                    b.Navigation("Employee");

                    b.Navigation("Item");

                    b.Navigation("Supplier");
                });

            modelBuilder.Entity("Domain.Entities.InvUser", b =>
                {
                    b.HasOne("Domain.Entities.EmpEgx", "Employee")
                        .WithMany()
                        .HasForeignKey("UserCode")
                        .HasPrincipalKey("EmpCode")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.Navigation("Employee");
                });

            modelBuilder.Entity("Domain.Entities.Item", b =>
                {
                    b.HasOne("Domain.Entities.ItemCategory", "ItemCategory")
                        .WithMany("Items")
                        .HasForeignKey("CatgryCode")
                        .HasPrincipalKey("CatgryCode")
                        .OnDelete(DeleteBehavior.Restrict)
                        .IsRequired();

                    b.Navigation("ItemCategory");
                });

            modelBuilder.Entity("Domain.Entities.RolePermission", b =>
                {
                    b.HasOne("Domain.Entities.ApplicationRole", "Role")
                        .WithMany("RolePermissions")
                        .HasForeignKey("RoleId")
                        .OnDelete(DeleteBehavior.Cascade);

                    b.Navigation("Role");
                });

            modelBuilder.Entity("Domain.Entities.UserRole", b =>
                {
                    b.HasOne("Domain.Entities.ApplicationRole", "Role")
                        .WithMany("UserRoles")
                        .HasForeignKey("RoleId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.Navigation("Role");
                });

            modelBuilder.Entity("Microsoft.AspNetCore.Identity.IdentityRoleClaim<string>", b =>
                {
                    b.HasOne("Domain.Entities.ApplicationRole", null)
                        .WithMany()
                        .HasForeignKey("RoleId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();
                });

            modelBuilder.Entity("Microsoft.AspNetCore.Identity.IdentityUserClaim<string>", b =>
                {
                    b.HasOne("Domain.Entities.ApplicationUser", null)
                        .WithMany()
                        .HasForeignKey("UserId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();
                });

            modelBuilder.Entity("Microsoft.AspNetCore.Identity.IdentityUserLogin<string>", b =>
                {
                    b.HasOne("Domain.Entities.ApplicationUser", null)
                        .WithMany()
                        .HasForeignKey("UserId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();
                });

            modelBuilder.Entity("Microsoft.AspNetCore.Identity.IdentityUserRole<string>", b =>
                {
                    b.HasOne("Domain.Entities.ApplicationRole", null)
                        .WithMany()
                        .HasForeignKey("RoleId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.HasOne("Domain.Entities.ApplicationUser", null)
                        .WithMany()
                        .HasForeignKey("UserId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();
                });

            modelBuilder.Entity("Microsoft.AspNetCore.Identity.IdentityUserToken<string>", b =>
                {
                    b.HasOne("Domain.Entities.ApplicationUser", null)
                        .WithMany()
                        .HasForeignKey("UserId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();
                });

            modelBuilder.Entity("Domain.Entities.ApplicationRole", b =>
                {
                    b.Navigation("RolePermissions");

                    b.Navigation("UserRoles");
                });

            modelBuilder.Entity("Domain.Entities.ItemCategory", b =>
                {
                    b.Navigation("Items");
                });
#pragma warning restore 612, 618
        }
    }
}
