//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated by a tool.
//     Runtime Version:4.0.30319.42000
//
//     Changes to this file may cause incorrect behavior and will be lost if
//     the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace Infrastructure.Resources {
    using System;
    
    
    /// <summary>
    ///   A strongly-typed resource class, for looking up localized strings, etc.
    /// </summary>
    // This class was auto-generated by the StronglyTypedResourceBuilder
    // class via a tool like ResGen or Visual Studio.
    // To add or remove a member, edit your .ResX file then rerun ResGen
    // with the /str option, or rebuild your VS project.
    [global::System.CodeDom.Compiler.GeneratedCodeAttribute("System.Resources.Tools.StronglyTypedResourceBuilder", "18.0.0.0")]
    [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
    [global::System.Runtime.CompilerServices.CompilerGeneratedAttribute()]
    public class CommonResource {
        
        private static global::System.Resources.ResourceManager resourceMan;
        
        private static global::System.Globalization.CultureInfo resourceCulture;
        
        [global::System.Diagnostics.CodeAnalysis.SuppressMessageAttribute("Microsoft.Performance", "CA1811:AvoidUncalledPrivateCode")]
        internal CommonResource() {
        }
        
        /// <summary>
        ///   Returns the cached ResourceManager instance used by this class.
        /// </summary>
        [global::System.ComponentModel.EditorBrowsableAttribute(global::System.ComponentModel.EditorBrowsableState.Advanced)]
        public static global::System.Resources.ResourceManager ResourceManager {
            get {
                if (object.ReferenceEquals(resourceMan, null)) {
                    global::System.Resources.ResourceManager temp = new global::System.Resources.ResourceManager("Infrastructure.Resources.CommonResource", typeof(CommonResource).Assembly);
                    resourceMan = temp;
                }
                return resourceMan;
            }
        }
        
        /// <summary>
        ///   Overrides the current thread's CurrentUICulture property for all
        ///   resource lookups using this strongly typed resource class.
        /// </summary>
        [global::System.ComponentModel.EditorBrowsableAttribute(global::System.ComponentModel.EditorBrowsableState.Advanced)]
        public static global::System.Globalization.CultureInfo Culture {
            get {
                return resourceCulture;
            }
            set {
                resourceCulture = value;
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Invalid request.
        /// </summary>
        public static string BadRequest {
            get {
                return ResourceManager.GetString("BadRequest", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Configure System Settings.
        /// </summary>
        public static string ConfigureSystemSettings {
            get {
                return ResourceManager.GetString("ConfigureSystemSettings", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Current Balance.
        /// </summary>
        public static string CurrnetBalance {
            get {
                return ResourceManager.GetString("CurrnetBalance", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Dead Stock Entry.
        /// </summary>
        public static string DeadStockEntry {
            get {
                return ResourceManager.GetString("DeadStockEntry", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Home.
        /// </summary>
        public static string Home {
            get {
                return ResourceManager.GetString("Home", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Incoming Items Returns.
        /// </summary>
        public static string IncomingItemsReturns {
            get {
                return ResourceManager.GetString("IncomingItemsReturns", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Inventory.
        /// </summary>
        public static string Inventory {
            get {
                return ResourceManager.GetString("Inventory", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to InventoryMovement.
        /// </summary>
        public static string InventoryMovement {
            get {
                return ResourceManager.GetString("InventoryMovement", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Issued Items Returns.
        /// </summary>
        public static string IssuedItemsReturns {
            get {
                return ResourceManager.GetString("IssuedItemsReturns", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Item balances.
        /// </summary>
        public static string ItemBalances {
            get {
                return ResourceManager.GetString("ItemBalances", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Item Codes.
        /// </summary>
        public static string ItemCodes {
            get {
                return ResourceManager.GetString("ItemCodes", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Main Category Classification.
        /// </summary>
        public static string MainCategoryClassification {
            get {
                return ResourceManager.GetString("MainCategoryClassification", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Main Items.
        /// </summary>
        public static string MainItems {
            get {
                return ResourceManager.GetString("MainItems", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Manage System Users.
        /// </summary>
        public static string ManageSystemUsers {
            get {
                return ResourceManager.GetString("ManageSystemUsers", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Resource not found.
        /// </summary>
        public static string NotFound {
            get {
                return ResourceManager.GetString("NotFound", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Post Daily Transactions.
        /// </summary>
        public static string PostDailyTransactions {
            get {
                return ResourceManager.GetString("PostDailyTransactions", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Record goods issued from the warehouse.
        /// </summary>
        public static string Recordgoodsissuedfromthewarehouse {
            get {
                return ResourceManager.GetString("Recordgoodsissuedfromthewarehouse", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Record goods received into the warehouse.
        /// </summary>
        public static string Recordgoodsreceivedintothewarehouse {
            get {
                return ResourceManager.GetString("Recordgoodsreceivedintothewarehouse", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Record Returns.
        /// </summary>
        public static string RecordReturns {
            get {
                return ResourceManager.GetString("RecordReturns", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Record transfers between warehouses.
        /// </summary>
        public static string Recordtransfersbetweenwarehouses {
            get {
                return ResourceManager.GetString("Recordtransfersbetweenwarehouses", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Reports.
        /// </summary>
        public static string Reports {
            get {
                return ResourceManager.GetString("Reports", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Save.
        /// </summary>
        public static string Save {
            get {
                return ResourceManager.GetString("Save", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Search &amp; Inquiry.
        /// </summary>
        public static string SearchAndInquiry {
            get {
                return ResourceManager.GetString("SearchAndInquiry", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to An unexpected error occurred.
        /// </summary>
        public static string ServerError {
            get {
                return ResourceManager.GetString("ServerError", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Subcategory classification.
        /// </summary>
        public static string SubcategoryClassification {
            get {
                return ResourceManager.GetString("SubcategoryClassification", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Supplier codes.
        /// </summary>
        public static string SupplierCodes {
            get {
                return ResourceManager.GetString("SupplierCodes", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to System Management.
        /// </summary>
        public static string SystemManagement {
            get {
                return ResourceManager.GetString("SystemManagement", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to  Something went wrong. Please contact support..
        /// </summary>
        public static string UnexpectedErrorDetail {
            get {
                return ResourceManager.GetString("UnexpectedErrorDetail", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Updated Successfully.
        /// </summary>
        public static string UpdateSuccess {
            get {
                return ResourceManager.GetString("UpdateSuccess", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Validation error occurred.
        /// </summary>
        public static string ValidationError {
            get {
                return ResourceManager.GetString("ValidationError", resourceCulture);
            }
        }
    }
}
